services:
  server:
    build: ./server
    restart: unless-stopped
    env_file: .env
    networks:
      - app

  client:
    build: ./client
    restart: unless-stopped
    ports:
      - "30200:80"
    depends_on:
      - server
    networks:
      - app

networks:
  app:
